# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  format:
    runs-on: self-hosted
    # Map a step output to a job output
    steps:
    - id: step1
      run: astyle --style=java -r "*.java" -n
  build:
    runs-on: self-hosted
    needs: format
    steps:
    - run: mvn -B package --file pom.xml
  test:
      runs-on: self-hosted
      needs: build
      steps:
      - run: mvn verify
  deploy:
      runs-on: ubuntu-latest
      needs: test
      steps:
        - run: mkdir ~/.ssh
        - run: echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        - run: touch ~/.ssh/id_rsa
        - run: chmod 600 ~/.ssh/id_rsa
        - run: echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        - run: scp -i ~/.ssh/id_rsa -r $(pwd) app@ec2-13-48-195-80.eu-north-1.compute.amazonaws.com
      env:
        SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
        SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}
